#!/bin/bash
echo "SlackDVD Installer"
echo "------------------"
echo ""
echo "===>Creating SlackDVD live installation on ${1}"
slackdvd_path="https://mirrors.slackware.bg/slackware/slackware64-current-iso/slackware64-current-install-dvd.iso"
echo "Downloading SlackDVD ISO to /tmp..."
curl -L -o /tmp/slackdvd.iso $slackdvd_path
echo "Writing ISO to disk..."
dd if=/tmp/slackdvd.iso of=$1
echo "Removing SlackDVD iso..."
rm /tmp/slackdvd.iso
echo "Completed!"
